//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
MIT License

Copyright (c) 2021 Open Traffic Generator

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTG) DeepCopyInto(out *IxiaTG) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTG.
func (in *IxiaTG) DeepCopy() *IxiaTG {
	if in == nil {
		return nil
	}
	out := new(IxiaTG)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IxiaTG) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGIntf) DeepCopyInto(out *IxiaTGIntf) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGIntf.
func (in *IxiaTGIntf) DeepCopy() *IxiaTGIntf {
	if in == nil {
		return nil
	}
	out := new(IxiaTGIntf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGIntfStatus) DeepCopyInto(out *IxiaTGIntfStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGIntfStatus.
func (in *IxiaTGIntfStatus) DeepCopy() *IxiaTGIntfStatus {
	if in == nil {
		return nil
	}
	out := new(IxiaTGIntfStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGList) DeepCopyInto(out *IxiaTGList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IxiaTG, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGList.
func (in *IxiaTGList) DeepCopy() *IxiaTGList {
	if in == nil {
		return nil
	}
	out := new(IxiaTGList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IxiaTGList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGSpec) DeepCopyInto(out *IxiaTGSpec) {
	*out = *in
	if in.ApiEndPoint != nil {
		in, out := &in.ApiEndPoint, &out.ApiEndPoint
		*out = make(map[string]IxiaTGSvcPort, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]IxiaTGIntf, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGSpec.
func (in *IxiaTGSpec) DeepCopy() *IxiaTGSpec {
	if in == nil {
		return nil
	}
	out := new(IxiaTGSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGStatus) DeepCopyInto(out *IxiaTGStatus) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]IxiaTGIntfStatus, len(*in))
		copy(*out, *in)
	}
	in.ApiEndPoint.DeepCopyInto(&out.ApiEndPoint)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGStatus.
func (in *IxiaTGStatus) DeepCopy() *IxiaTGStatus {
	if in == nil {
		return nil
	}
	out := new(IxiaTGStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGSvcEP) DeepCopyInto(out *IxiaTGSvcEP) {
	*out = *in
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGSvcEP.
func (in *IxiaTGSvcEP) DeepCopy() *IxiaTGSvcEP {
	if in == nil {
		return nil
	}
	out := new(IxiaTGSvcEP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGSvcPort) DeepCopyInto(out *IxiaTGSvcPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGSvcPort.
func (in *IxiaTGSvcPort) DeepCopy() *IxiaTGSvcPort {
	if in == nil {
		return nil
	}
	out := new(IxiaTGSvcPort)
	in.DeepCopyInto(out)
	return out
}
