//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTG) DeepCopyInto(out *IxiaTG) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTG.
func (in *IxiaTG) DeepCopy() *IxiaTG {
	if in == nil {
		return nil
	}
	out := new(IxiaTG)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IxiaTG) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGIntf) DeepCopyInto(out *IxiaTGIntf) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGIntf.
func (in *IxiaTGIntf) DeepCopy() *IxiaTGIntf {
	if in == nil {
		return nil
	}
	out := new(IxiaTGIntf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGIntfStatus) DeepCopyInto(out *IxiaTGIntfStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGIntfStatus.
func (in *IxiaTGIntfStatus) DeepCopy() *IxiaTGIntfStatus {
	if in == nil {
		return nil
	}
	out := new(IxiaTGIntfStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGList) DeepCopyInto(out *IxiaTGList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IxiaTG, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGList.
func (in *IxiaTGList) DeepCopy() *IxiaTGList {
	if in == nil {
		return nil
	}
	out := new(IxiaTGList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IxiaTGList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGSpec) DeepCopyInto(out *IxiaTGSpec) {
	*out = *in
	if in.ApiEndPoint != nil {
		in, out := &in.ApiEndPoint, &out.ApiEndPoint
		*out = make(map[string]IxiaTGSvcPort, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]IxiaTGIntf, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGSpec.
func (in *IxiaTGSpec) DeepCopy() *IxiaTGSpec {
	if in == nil {
		return nil
	}
	out := new(IxiaTGSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGStatus) DeepCopyInto(out *IxiaTGStatus) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]IxiaTGIntfStatus, len(*in))
		copy(*out, *in)
	}
	in.ApiEndPoint.DeepCopyInto(&out.ApiEndPoint)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGStatus.
func (in *IxiaTGStatus) DeepCopy() *IxiaTGStatus {
	if in == nil {
		return nil
	}
	out := new(IxiaTGStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGSvcEP) DeepCopyInto(out *IxiaTGSvcEP) {
	*out = *in
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGSvcEP.
func (in *IxiaTGSvcEP) DeepCopy() *IxiaTGSvcEP {
	if in == nil {
		return nil
	}
	out := new(IxiaTGSvcEP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IxiaTGSvcPort) DeepCopyInto(out *IxiaTGSvcPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IxiaTGSvcPort.
func (in *IxiaTGSvcPort) DeepCopy() *IxiaTGSvcPort {
	if in == nil {
		return nil
	}
	out := new(IxiaTGSvcPort)
	in.DeepCopyInto(out)
	return out
}
