name: CICD

env:
  PYTHON_VERSION: "3.8"
  GO_VERSION: "1.19"

on:
  push:

jobs:
  sanity:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout source
          uses: actions/checkout@v3
        - name: Setup docker
          uses: docker-practice/actions-setup-docker@master
        - name: Setup Go
          uses: actions/setup-go@v3
          with:
            go-version: ${{ env.GO_VERSION }}
        - name: Setup KNE cluster
          run: |
            GITHUB_USER=${{ secrets.ENV_GITHUB_USER }} GITHUB_PAT=${{ secrets.ENV_GITHUB_PAT }} ./deploy.sh new_k8s_cluster kne
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ env.PYTHON_VERSION }}
        - name: Setup sanity prerequisites
          run: |
            ./deploy.sh prepytest
        # - name: Run Python tests
        #   run: |
        #     ./do.sh pytest ./feature/b2b/
        # - name: Archive logs
        #   if: always()
        #   uses: actions/upload-artifact@v3
        #   with:
        #     name: kne_b2b_py
        #     path: |
        #       logs
        # - name: Teardown KNE OTG back-to-back topology
        #   run: |
        #     ./do.sh topo rm kneb2b